const CANVAS_HEIGHT = 300;
const CANVAS_WIDTH = 300;
const MAX_IMAGE_SIZE = 100;
const MIN_IMAGE_SIZE = 1;
const CUT_IFRAME_WIDTH = 2;

export {
  CANVAS_HEIGHT,
  CANVAS_WIDTH,
  MAX_IMAGE_SIZE,
  MIN_IMAGE_SIZE,
  CUT_IFRAME_WIDTH,
};
